Repository borgbackup/borg, pull requests merged in 2019-02, with the labels that each got.

#4276 make "hostname" short, even on misconfigured systems, fixes #4262
  src/borg/platform/base.py
Labels: backport/1.1-maint

#4301 update release workflow using twine (docs, scripts), see #4213
  docs/development.rst
  requirements.d/development.txt
  scripts/release
  scripts/sdist-sign
  scripts/upload-pypi
Labels: backport/1.0-maint, backport/1.1-maint

#4318 work around the backslash issue, see #4280
  src/borg/archiver.py
Labels: forwardport/master

#4317 work around some Microsoft WSL issues
  src/borg/helpers.py
  src/borg/platform/base.py
  src/borg/platform/darwin.pyx
  src/borg/platform/freebsd.pyx
  src/borg/platform/linux.pyx
Labels: forwardport/master

#4316 borg init --make-parent-dirs parent1/parent2/repo_dir, fixes #4235
  src/borg/archiver.py
  src/borg/remote.py
  src/borg/repository.py
  src/borg/testsuite/archiver.py
Labels: backport/1.1-maint

#4331 borg mount / borgfs security fix (1.1-maint)
  src/borg/archiver.py
  src/borg/fuse.py
Labels: backport/1.0-maint, forwardport/master, security

#4285 add warnings on repository copies to avoid future problem like #4272
  docs/faq.rst
Labels: backport/1.1-maint

#4378 Emit user-friendly error if repo key is exported to a directory
  src/borg/archiver.py
  src/borg/testsuite/archiver.py
Labels: backport/1.1-maint

#4390 Fix valid archive keys, add comments.
  src/borg/constants.py
  src/borg/helpers/checks.py
  src/borg/item.pyx
Labels: backport/1.1-maint
