Repository borgbackup/borg, pull requests merged in 2022-04, with the labels that each got.

#6568 Remove stray punctuation from secure-erase message
  src/borg/repository.py
Labels: backport/1.1-maint, backport/1.2-maint

#6541 borg check improvements (1.1)
  src/borg/archive.py
Labels: forwardport/master, backport/1.2-maint

#6564 load_key: no key is same as empty key, fixes #6441
  src/borg/crypto/key.py
  src/borg/crypto/keymanager.py
  src/borg/repository.py
Labels: backport/1.1-maint, backport/1.2-maint

#6599 setup.cfg: setup_requires setuptools_scm
  setup.cfg
Labels: backport/1.2-maint

#6615 diff: support presence change for blkdev, chrdev and fifo items (1.2-maint)
  src/borg/item.pyx
Labels: backport/1.1-maint, forwardport/master

#6616 fix transaction rollback: use files cache filename as found in txn.active
  src/borg/cache.py
Labels: backport/1.1-maint, backport/1.2-maint
