Repository borgbackup/borg, pull requests merged in 2024-01, with the labels that each got.

#7976 optional more specific return codes
  docs/internals/frontends.rst
  docs/usage/general/environment.rst.inc
  docs/usage/general/return-codes.rst.inc
  scripts/errorlist.py
  src/borg/archive.py
  src/borg/archiver.py
  src/borg/cache.py
  src/borg/constants.py
  src/borg/crypto/file_integrity.py
  src/borg/crypto/key.py
  src/borg/crypto/keymanager.py
  src/borg/helpers/__init__.py
  src/borg/helpers/checks.py
  src/borg/helpers/errors.py
  src/borg/helpers/fs.py
  src/borg/helpers/manifest.py
  src/borg/helpers/parseformat.py
  src/borg/locking.py
  src/borg/remote.py
  src/borg/repository.py
  src/borg/testsuite/archiver.py
  src/borg/testsuite/helpers.py
Labels: forwardport/master

#8034 add script for fetching borg binaries from VMs, fixes #7989
  scripts/fetch-binaries
Labels: port/master

#8033 fix CommandError args, fixes #8029
  src/borg/archiver.py
Labels: port/master

#8043 logger method params (1.4-maint)
  src/borg/logger.py
Labels: port/master

#6052 Create and use Brewfile
  .github/workflows/ci.yml
  Brewfile
  docs/development.rst
  docs/installation.rst
Labels: port/1.4-maint

#8047 repository: give clean error msg for invalid nonce file, see #7967
  src/borg/archiver.py
  src/borg/cache.py
  src/borg/crypto/key.py
  src/borg/crypto/keymanager.py
  src/borg/crypto/nonces.py
  src/borg/helpers/parseformat.py
  src/borg/remote.py
  src/borg/repository.py
  src/borg/testsuite/archiver.py
  src/borg/testsuite/checksums.py
  src/borg/testsuite/chunker_slow.py
  src/borg/testsuite/crypto.py
  src/borg/testsuite/key.py
Labels: port/master

#8053 implement "borg version", fixes #7829
  src/borg/archiver.py
Labels: port/master

#8054 more specific errors / msgids (1.4-maint)
  docs/internals/frontends.rst
  src/borg/remote.py
  src/borg/repository.py
Labels: port/master

#8065 Use less setup.py (1.4-maint)
  docs/development.rst
  docs/installation.rst
  docs/usage/mount.rst
  pyproject.toml
  scripts/gendocs.py
  setup.py
  src/borg/archiver.py
  src/borg/helpers/msgpack.py
Labels: port/master

#8067 gh actions: increase timeout (1.4-maint)
  .github/workflows/ci.yml
Labels: port/master, port/1.2-maint

#8060 slashdot hack (1.4-maint)
  docs/usage/create.rst
  src/borg/archive.py
  src/borg/archiver.py
  src/borg/helpers/fs.py
  src/borg/testsuite/archiver.py
Labels: port/master

#8069 Use less setup.py, continued (1.4-maint)
  Vagrantfile
  docs/development.rst
  pyproject.toml
  scripts/make.py
  setup.py
Labels: port/master
